projects:
  u3infotech:
    schemaPath: 
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
