// loaders
export const ENABLE_LOADER = 'ENABLE_LOADER';
export const DISABLE_LOADER = 'DISABLE_LOADER';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// onboarding
export const ONBOARDING_UPDATE = 'ONBOARDING_UPDATE';
export const CREATE_ATHLETE_AND_ACCOUNT = 'CREATE_ATHLETE_AND_ACCOUNT';
export const CREATE_ATHLETE = 'CREATE_ATHLETE';
export const CLEAR_ONBOARDING_STATE = 'CLEAR_ONBOARDING_STATE';

// user
export const USER_UPDATE = 'USER_UPDATE';
export const GET_USER_BY_PHONE = 'GET_USER_BY_PHONE';
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';

// user/login
export const ONBOARDING_SILENT_SIGN_IN = 'ONBOARDING_SILENT_SIGN_IN';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const LOG_OUT = 'LOG_OUT';

// banking
export const UPDATE_HOME_STEP = 'UPDATE_HOME_STEP';
export const UPDATE_POD_SETTINGS = 'UPDATE_POD_SETTINGS';
export const POD_SETTINGS_UPDATED = 'POD_SETTINGS_UPDATED';
export const GET_RECENT_TRANSACTIONS = 'GET_RECENT_TRANSACTIONS';
export const RECENT_TRANSACTIONS_LOADED = 'RECENT_TRANSACTIONS_LOADED';
export const MARK_RECENT_TRANSACTION_READ = 'MARK_RECENT_TRANSACTION_READ';
export const GET_CONNECTED_ACCOUNTS = 'GET_CONNECTED_ACCOUNTS';
export const PLAID_ACCOUNTS_LOADED = 'PLAID_ACCOUNTS_LOADED';
export const PLAID_ACCOUNT_SELECTED = 'PLAID_ACCOUNT_SELECTED';
export const TRANSFER_AMOUNT_ENTERED = 'TRANSFER_AMOUNT_ENTERED';
export const CREATE_DEPOSIT = 'CREATE_DEPOSIT';
export const GET_ATHLETE_ACCOUNTS = 'GET_ATHLETE_ACCOUNTS';
export const ATHLETE_ACCOUNTS_LOADED = 'ATHLETE_ACCOUNTS_LOADED';
export const GET_BALANCE_HISTORY = 'GET_BALANCE_HISTORY';
export const BALANCE_HISTORY_LOADED = 'BALANCE_HISTORY_LOADED';
export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const TRANSACTION_HISTORY_LOADED = 'TRANSACTION_HISTORY_LOADED';
export const INITIATE_UNIT_VERIFICATION = 'INITIATE_UNIT_VERIFICATION';
export const UNIT_VERIFICATION_TOKEN_LOADED = 'UNIT_VERIFICATION_TOKEN_LOADED';
export const SET_UNIT_VERIFICATION_CODE_VALIDITY =
  'SET_UNIT_VERIFICATION_CODE_VALIDITY';
export const VERIFY_UNIT_CHALLENGE_CODE = 'VERIFY_UNIT_CHALLENGE_CODE';
export const SET_UNIT_TOKEN = 'SET_UNIT_TOKEN';
export const CLEAR_BANKING_STATE = 'CLEAR_BANKING_STATE';

// wyre
export const OPEN_REWARDS_ACCOUNT = 'OPEN_REWARDS_ACCOUNT';
export const WYRE_PURCHASE_AMOUNT_ENTERED = 'WYRE_PURCHASE_AMOUNT_ENTERED';
export const WYRE_PURCHASE_REQUEST = 'WYRE_PURCHASE_REQUEST';
export const WYRE_WITHDRAW_AMOUNT_ENTERED = 'WYRE_WITHDRAW_AMOUNT_ENTERED';
export const WYRE_WITHDRAW_REQUEST = 'WYRE_WITHDRAW_REQUEST';
export const GET_WYRE_ACCOUNT = 'GET_WYRE_ACCOUNT';
export const WYRE_ACCOUNT_LOADED = 'WYRE_ACCOUNT_LOADED';
export const CLEAR_WYRE_STATE = 'CLEAR_WYRE_STATE';

// opportunities
export const LOAD_LEARN_STATUSES = 'LOAD_LEARN_STATUSES';
export const LOAD_LEARNS = 'LOAD_LEARNS';
export const LOAD_REWARDS = 'LOAD_REWARDS';
export const LOAD_EVENTS = 'LOAD_EVENTS';

export const UPDATE_LEARN_STATUS = 'UPDATE_LEARN_STATUS';
export const UPDATE_LEARN_STATUSES = 'UPDATE_LEARN_STATUSES';
export const UPDATE_LEARNS = 'UPDATE_LEARNS';
export const UPDATE_REWARDS = 'UPDATE_REWARDS';
export const UPDATE_REWARD = 'UPDATE_REWARD';
export const UPDATE_EVENTS = 'UPDATE_EVENTS';
export const UPDATE_EVENT = 'UPDATE_EVENT';

// navigation
export const UPDATE_ACTIVE_ROUTE_NAME = 'UPDATE_ACTIVE_ROUTE_NAME';